# Generated by Django 5.0.1 on 2026-02-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_battery_product_camera_product_ram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
