# Generated by Django 5.0.1 on 2026-02-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compatible_accessories',
            field=models.ManyToManyField(blank=True, related_name='main_products', to='store.product'),
        ),
    ]
